# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page_Gui_Test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 869)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 10, 301, 61))
        font = QtGui.QFont()
        font.setFamily("휴먼둥근헤드라인")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("   color: black;\n"
"   background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"   border-radius: 30px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 200, 111, 30))
        self.label_2.setStyleSheet("color: rgb(170, 0, 255);\n"
"background-color: white;\n"
"border: 2px solid rgb(170, 0, 255);\n"
"border-radius: 15px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 283, 111, 30))
        self.label_4.setStyleSheet("color: rgb(170, 0, 255);\n"
"background-color: white;\n"
"border: 2px solid rgb(170, 0, 255);\n"
"border-radius: 15px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.Store_Name = QtWidgets.QLineEdit(self.centralwidget)
        self.Store_Name.setGeometry(QtCore.QRect(420, 205, 113, 20))
        self.Store_Name.setObjectName("Store_Name")
        self.Star_Total = QtWidgets.QLineEdit(self.centralwidget)
        self.Star_Total.setGeometry(QtCore.QRect(420, 288, 113, 20))
        self.Star_Total.setObjectName("Star_Total")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 80, 251, 231))
        self.graphicsView.setStyleSheet("border-image:url(\"C:/Users/loisk/PycharmProjects/gp_team/yj.jpg\");")
        self.graphicsView.setObjectName("graphicsView")
        self.Review_Count_total = QtWidgets.QLineEdit(self.centralwidget)
        self.Review_Count_total.setGeometry(QtCore.QRect(690, 204, 111, 20))
        self.Review_Count_total.setObjectName("Review_Count_total")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(570, 200, 111, 30))
        self.label_5.setStyleSheet("color: rgb(170, 0, 255);\n"
"background-color: white;\n"
"border: 2px solid rgb(170, 0, 255);\n"
"border-radius: 15px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(300, 320, 111, 30))
        self.label_6.setStyleSheet("color: rgb(170, 0, 255);\n"
"background-color: white;\n"
"border: 2px solid rgb(170, 0, 255);\n"
"border-radius: 15px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.Negative_Review = QtWidgets.QLineEdit(self.centralwidget)
        self.Negative_Review.setGeometry(QtCore.QRect(691, 325, 111, 20))
        self.Negative_Review.setObjectName("Negative_Review")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 320, 111, 30))
        self.label_7.setStyleSheet("color: rgb(170, 0, 255);\n"
"background-color: white;\n"
"border: 2px solid rgb(170, 0, 255);\n"
"border-radius: 15px;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.Positive_Review = QtWidgets.QLineEdit(self.centralwidget)
        self.Positive_Review.setGeometry(QtCore.QRect(420, 326, 113, 20))
        self.Positive_Review.setObjectName("Positive_Review")
        self.Find_Store_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.Find_Store_Btn.setGeometry(QtCore.QRect(720, 77, 91, 41))
        font = QtGui.QFont()
        font.setFamily("휴먼옛체")
        font.setPointSize(16)
        self.Find_Store_Btn.setFont(font)
        self.Find_Store_Btn.setStyleSheet("color: white;\n"
"    background-color: rgb(170, 0, 255);\n"
"    border-radius: 20px;")
        self.Find_Store_Btn.setObjectName("Find_Store_Btn")
        self.Input_Store = QtWidgets.QLineEdit(self.centralwidget)
        self.Input_Store.setGeometry(QtCore.QRect(430, 82, 271, 31))
        self.Input_Store.setText("")
        self.Input_Store.setObjectName("Input_Store")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(300, 80, 111, 31))
        self.label_8.setStyleSheet("color: rgb(170, 0, 255);\n"
"background-color: white;\n"
"border: 2px solid rgb(170, 0, 255);\n"
"border-radius: 15px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(350, 160, 431, 23))
        self.progressBar.setMinimum(100)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 320, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 320, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 400, 811, 401))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(700, 10, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_2.setGeometry(QtCore.QRect(30, 80, 331, 251))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_3.setGeometry(QtCore.QRect(410, 80, 331, 251))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 271, 16))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_4.setGeometry(QtCore.QRect(10, 30, 371, 331))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_5.setGeometry(QtCore.QRect(410, 30, 341, 331))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(420, 10, 121, 16))
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.listView = QtWidgets.QListView(self.tab_3)
        self.listView.setGeometry(QtCore.QRect(330, 30, 431, 301))
        self.listView.setObjectName("listView")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(40, 20, 171, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_3, "")
        self.Star_Total_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Star_Total_2.setGeometry(QtCore.QRect(690, 284, 113, 20))
        self.Star_Total_2.setObjectName("Star_Total_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(570, 280, 111, 30))
        self.label_9.setStyleSheet("color: rgb(170, 0, 255);\n"
"background-color: white;\n"
"border: 2px solid rgb(170, 0, 255);\n"
"border-radius: 15px;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionshow = QtWidgets.QAction(MainWindow)
        self.actionshow.setObjectName("actionshow")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Find_Store_Btn.clicked.connect(MainWindow.start) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'휴먼둥근헤드라인\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">음식점 정보</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "STORE NAME"))
        self.label_4.setText(_translate("MainWindow", "사이트 별점"))
        self.label_5.setText(_translate("MainWindow", "Total Comment"))
        self.label_6.setText(_translate("MainWindow", "긍정 댓글 수"))
        self.label_7.setText(_translate("MainWindow", "부정 댓글 수"))
        self.Find_Store_Btn.setText(_translate("MainWindow", "search"))
        self.label_8.setText(_translate("MainWindow", "STORE"))
        self.pushButton.setText(_translate("MainWindow", "이전"))
        self.pushButton_2.setText(_translate("MainWindow", "다음"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.label_11.setText(_translate("MainWindow", "사이트 평점 Vs. 학습한 평점 비교"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_12.setText(_translate("MainWindow", "부정 WordCloud"))
        self.label_13.setText(_translate("MainWindow", "긍정 WordCloud"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label_10.setText(_translate("MainWindow", "MENU TOP 5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 3"))
        self.label_9.setText(_translate("MainWindow", "학습한 별점"))
        self.actionshow.setText(_translate("MainWindow", "show"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
